services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_APP_NAME=${VITE_APP_NAME}
    container_name: netbase-fe
    restart: always
    environment:
      TZ: Asia/Jakarta
    ports:
      - "127.0.0.1:${PORT:-3000}:80"
